name: Pull Request Check

on:
  pull_request:
    branches: [ main, develop ]
    paths:
            - 'force-app/**'
            
jobs:
  source_code_analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3
        
      - name: Run PMD Apex Code Scan
        uses: pmd/pmd-github-action@v1
        with:
          rulesets: 'custom-apex-rules.xml'
          sourcePath: './force-app/main/default/classes'
          analyzeModifiedFilesOnly: false
        
  run_unit_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}
        fetch-depth: 0
    - uses: actions/setup-node@v1
      with:
        node-version: '>=14'
        check-latest: true
                      
    - name: Install Salesforce CLI
      run: |
        npm install @salesforce/cli --location=global
        echo "$(npm config get prefix)/bin" >> $GITHUB_PATH
        sf version  
    
    - name: Authenticate with Dev Hub
      run: |
        echo ${{ secrets.DEVHUB_TOKEN }} > sf_auth_url.txt
        sf org login sfdx-url -f sf_auth_url.txt --alias DevHub --set-default-dev-hub
        rm -f ./sf_auth_url.txt
        
    - name: Create Scratch Org
      run: 'sf org create scratch --definition-file config/project-scratch-def.json -a ${{ github.head_ref }} -d'
      
    - name: Push Source
      run: 'sf project deploy start --target-org ${{ github.head_ref }}'
      
    - name: Run Apex Tests
      run: 'sf apex run test -o ${{ github.head_ref }} -r human --synchronous'
      
    - name: Delete Scratch Org
      if: always()
      run: 'sf org delete scratch --no-prompt --target-org ${{ github.head_ref }}'